### PR TITLE
[CL][89149004] added updated_form event trigger, bumped version

### PR DESCRIPTION
**Pull request by cleathers**
# [Story](https://www.pivotaltracker.com/story/show/89149004)

## What I did
- bumped version number
- added event trigger for Form update

### CODE REVIEW

**Comment by pasha** [comment]
:+1:

**Comment by warrenv** [comment]
Shouldn't the .coffee file be modified instead of the .js file in dist/?

**Comment by pasha** [comment]
good catch @warrenv

**Comment by cleathers** [comment]
I'm not entirely sure. I just know that on the last PR I did I had made a change to the js file and I saw the changes push through to the app. @lfender6445 am I supposed to be changing the .coffee file?

**Comment by pasha** [comment]
@cleathers if you update .coffee and run gulp it will compile .js version too.

**Comment by lfender6445** [comment]
echo what pasha said - by running gulp, we can build coffee to dist directory

**Comment by cleathers** [comment]
Oh, so the process is supposed to go something like this:
1) Change Coffee Files
2) Run gulp locally
3) Push updated files to this repo

I didn't realize we were supposed to manually run gulp before pushing. Is this correct? Or is the rent app supposed to compile the coffee files?

**Comment by lfender6445** [comment]
think of the repo as its own mini application - we build here, rent compiles ALL assets via tautline into single file. but the bits and pieces that make up that main file come from external repos like this one that have their own build process

**Comment by lfender6445** [comment]
FWIW checkout bower link - you can test your application changes locally in the rent application to make sure everything is working in advance

https://github.com/rentpath/idg/wiki/Bower-Conversion#bower-link--local-package-development

**Comment by cleathers** [comment]
Ok that makes more sense. Thanks for the explanation and link @lfender6445! I'll make the necessary changes shortly.

**Pull request closed without merging**
