### PR TITLE
[CL][891490004] Added event triggers to coffee files instead of main dist file

### PR DESCRIPTION
**Pull request by cleathers**
This PR is a result of issues found in PR#8
https://github.com/rentpath/jquery-movingservice/pull/8

Thanks for your help @pasha, @warrenv and @lfender6445! Let me know if anything else seems off.

### CODE REVIEW

**Comment by pasha** [comment]
:+1:

**Comment by lfender6445** [comment]
project was missing bowerrc so i added it in this branch, hope you don't mind. :+1:

**Comment by lfender6445** [comment]
@cleathers - also may sure you tag a new version via git

**Comment by cleathers** [comment]
Tagged the new version in git as v1.0.3

**Pull request merged**
